spring:
  datasource:
    url: jdbc:mysql://192.168.31.20:3306/test?autoreconnect=true&useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull
    username: root
    password: tigerli199351.
    driver-class: com.mysql.jdbc.Driver